//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.TestGenDefault
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Book.
    /// </summary>
    //  *** Start programmer edit section *** (Book CustomAttributes)

    //  *** End programmer edit section *** (Book CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BookE", new string[] {
            "Name as \'Name\'",
            "Capacity as \'Capacity\'",
            "Annotation as \'Annotation\'",
            "Agenda as \'Agenda\'",
            "PicturesAuthor as \'Pictures author\'",
            "Reaction as \'Reaction\'",
            "Copyright as \'Copyright\'",
            "LibraryCode as \'Library code\'",
            "Tags as \'Tags\'",
            "Topic as \'Topic\'",
            "Theme as \'Theme\'",
            "Corrector as \'Corrector\'",
            "Format as \'Format\'",
            "Font as \'Font\'",
            "PublishDate as \'Publish date\'",
            "Bestseller as \'Bestseller\'",
            "Language as \'Language\'",
            "Language.Name as \'Name\'",
            "Author as \'Author\'",
            "Author.Name as \'Name\'",
            "Country as \'Country\'",
            "Country.Name as \'Name\'"})]
    [View("BookL", new string[] {
            "Name as \'Name\'",
            "Capacity as \'Capacity\'",
            "Annotation as \'Annotation\'",
            "Agenda as \'Agenda\'",
            "PicturesAuthor as \'Pictures author\'",
            "Reaction as \'Reaction\'",
            "Copyright as \'Copyright\'",
            "LibraryCode as \'Library code\'",
            "Tags as \'Tags\'",
            "Topic as \'Topic\'",
            "Theme as \'Theme\'",
            "Corrector as \'Corrector\'",
            "Format as \'Format\'",
            "Font as \'Font\'",
            "PublishDate as \'Publish date\'",
            "Bestseller as \'Bestseller\'",
            "Language.Name as \'Name\'",
            "Author.Name as \'Name\'",
            "Country.Name as \'Name\'"})]
    public class Book : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private int fCapacity;
        
        private string fAnnotation;
        
        private string fAgenda;
        
        private string fPicturesAuthor;
        
        private string fReaction;
        
        private string fCopyright;
        
        private string fLibraryCode;
        
        private string fTags;
        
        private string fTheme;
        
        private string fTopic;
        
        private string fCorrector;
        
        private string fFormat;
        
        private string fFont;
        
        private System.DateTime fPublishDate;
        
        private bool fBestseller;
        
        private NewPlatform.TestGenDefault.Language fLanguage;
        
        private NewPlatform.TestGenDefault.Author fAuthor;
        
        private NewPlatform.TestGenDefault.Country fCountry;
        
        //  *** Start programmer edit section *** (Book CustomMembers)

        //  *** End programmer edit section *** (Book CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Name CustomAttributes)

        //  *** End programmer edit section *** (Book.Name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Name Get start)

                //  *** End programmer edit section *** (Book.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Book.Name Get end)

                //  *** End programmer edit section *** (Book.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Name Set start)

                //  *** End programmer edit section *** (Book.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Book.Name Set end)

                //  *** End programmer edit section *** (Book.Name Set end)
            }
        }
        
        /// <summary>
        /// Capacity.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Capacity CustomAttributes)

        //  *** End programmer edit section *** (Book.Capacity CustomAttributes)
        [NotNull()]
        public virtual int Capacity
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Capacity Get start)

                //  *** End programmer edit section *** (Book.Capacity Get start)
                int result = this.fCapacity;
                //  *** Start programmer edit section *** (Book.Capacity Get end)

                //  *** End programmer edit section *** (Book.Capacity Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Capacity Set start)

                //  *** End programmer edit section *** (Book.Capacity Set start)
                this.fCapacity = value;
                //  *** Start programmer edit section *** (Book.Capacity Set end)

                //  *** End programmer edit section *** (Book.Capacity Set end)
            }
        }
        
        /// <summary>
        /// Annotation.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Annotation CustomAttributes)

        //  *** End programmer edit section *** (Book.Annotation CustomAttributes)
        [StrLen(255)]
        public virtual string Annotation
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Annotation Get start)

                //  *** End programmer edit section *** (Book.Annotation Get start)
                string result = this.fAnnotation;
                //  *** Start programmer edit section *** (Book.Annotation Get end)

                //  *** End programmer edit section *** (Book.Annotation Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Annotation Set start)

                //  *** End programmer edit section *** (Book.Annotation Set start)
                this.fAnnotation = value;
                //  *** Start programmer edit section *** (Book.Annotation Set end)

                //  *** End programmer edit section *** (Book.Annotation Set end)
            }
        }
        
        /// <summary>
        /// Agenda.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Agenda CustomAttributes)

        //  *** End programmer edit section *** (Book.Agenda CustomAttributes)
        [StrLen(255)]
        public virtual string Agenda
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Agenda Get start)

                //  *** End programmer edit section *** (Book.Agenda Get start)
                string result = this.fAgenda;
                //  *** Start programmer edit section *** (Book.Agenda Get end)

                //  *** End programmer edit section *** (Book.Agenda Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Agenda Set start)

                //  *** End programmer edit section *** (Book.Agenda Set start)
                this.fAgenda = value;
                //  *** Start programmer edit section *** (Book.Agenda Set end)

                //  *** End programmer edit section *** (Book.Agenda Set end)
            }
        }
        
        /// <summary>
        /// PicturesAuthor.
        /// </summary>
        //  *** Start programmer edit section *** (Book.PicturesAuthor CustomAttributes)

        //  *** End programmer edit section *** (Book.PicturesAuthor CustomAttributes)
        [StrLen(255)]
        public virtual string PicturesAuthor
        {
            get
            {
                //  *** Start programmer edit section *** (Book.PicturesAuthor Get start)

                //  *** End programmer edit section *** (Book.PicturesAuthor Get start)
                string result = this.fPicturesAuthor;
                //  *** Start programmer edit section *** (Book.PicturesAuthor Get end)

                //  *** End programmer edit section *** (Book.PicturesAuthor Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.PicturesAuthor Set start)

                //  *** End programmer edit section *** (Book.PicturesAuthor Set start)
                this.fPicturesAuthor = value;
                //  *** Start programmer edit section *** (Book.PicturesAuthor Set end)

                //  *** End programmer edit section *** (Book.PicturesAuthor Set end)
            }
        }
        
        /// <summary>
        /// Reaction.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Reaction CustomAttributes)

        //  *** End programmer edit section *** (Book.Reaction CustomAttributes)
        [StrLen(255)]
        public virtual string Reaction
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Reaction Get start)

                //  *** End programmer edit section *** (Book.Reaction Get start)
                string result = this.fReaction;
                //  *** Start programmer edit section *** (Book.Reaction Get end)

                //  *** End programmer edit section *** (Book.Reaction Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Reaction Set start)

                //  *** End programmer edit section *** (Book.Reaction Set start)
                this.fReaction = value;
                //  *** Start programmer edit section *** (Book.Reaction Set end)

                //  *** End programmer edit section *** (Book.Reaction Set end)
            }
        }
        
        /// <summary>
        /// Copyright.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Copyright CustomAttributes)

        //  *** End programmer edit section *** (Book.Copyright CustomAttributes)
        [StrLen(255)]
        public virtual string Copyright
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Copyright Get start)

                //  *** End programmer edit section *** (Book.Copyright Get start)
                string result = this.fCopyright;
                //  *** Start programmer edit section *** (Book.Copyright Get end)

                //  *** End programmer edit section *** (Book.Copyright Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Copyright Set start)

                //  *** End programmer edit section *** (Book.Copyright Set start)
                this.fCopyright = value;
                //  *** Start programmer edit section *** (Book.Copyright Set end)

                //  *** End programmer edit section *** (Book.Copyright Set end)
            }
        }
        
        /// <summary>
        /// LibraryCode.
        /// </summary>
        //  *** Start programmer edit section *** (Book.LibraryCode CustomAttributes)

        //  *** End programmer edit section *** (Book.LibraryCode CustomAttributes)
        [StrLen(255)]
        public virtual string LibraryCode
        {
            get
            {
                //  *** Start programmer edit section *** (Book.LibraryCode Get start)

                //  *** End programmer edit section *** (Book.LibraryCode Get start)
                string result = this.fLibraryCode;
                //  *** Start programmer edit section *** (Book.LibraryCode Get end)

                //  *** End programmer edit section *** (Book.LibraryCode Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.LibraryCode Set start)

                //  *** End programmer edit section *** (Book.LibraryCode Set start)
                this.fLibraryCode = value;
                //  *** Start programmer edit section *** (Book.LibraryCode Set end)

                //  *** End programmer edit section *** (Book.LibraryCode Set end)
            }
        }
        
        /// <summary>
        /// Tags.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Tags CustomAttributes)

        //  *** End programmer edit section *** (Book.Tags CustomAttributes)
        [StrLen(255)]
        public virtual string Tags
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Tags Get start)

                //  *** End programmer edit section *** (Book.Tags Get start)
                string result = this.fTags;
                //  *** Start programmer edit section *** (Book.Tags Get end)

                //  *** End programmer edit section *** (Book.Tags Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Tags Set start)

                //  *** End programmer edit section *** (Book.Tags Set start)
                this.fTags = value;
                //  *** Start programmer edit section *** (Book.Tags Set end)

                //  *** End programmer edit section *** (Book.Tags Set end)
            }
        }
        
        /// <summary>
        /// Theme.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Theme CustomAttributes)

        //  *** End programmer edit section *** (Book.Theme CustomAttributes)
        [StrLen(255)]
        public virtual string Theme
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Theme Get start)

                //  *** End programmer edit section *** (Book.Theme Get start)
                string result = this.fTheme;
                //  *** Start programmer edit section *** (Book.Theme Get end)

                //  *** End programmer edit section *** (Book.Theme Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Theme Set start)

                //  *** End programmer edit section *** (Book.Theme Set start)
                this.fTheme = value;
                //  *** Start programmer edit section *** (Book.Theme Set end)

                //  *** End programmer edit section *** (Book.Theme Set end)
            }
        }
        
        /// <summary>
        /// Topic.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Topic CustomAttributes)

        //  *** End programmer edit section *** (Book.Topic CustomAttributes)
        [StrLen(255)]
        public virtual string Topic
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Topic Get start)

                //  *** End programmer edit section *** (Book.Topic Get start)
                string result = this.fTopic;
                //  *** Start programmer edit section *** (Book.Topic Get end)

                //  *** End programmer edit section *** (Book.Topic Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Topic Set start)

                //  *** End programmer edit section *** (Book.Topic Set start)
                this.fTopic = value;
                //  *** Start programmer edit section *** (Book.Topic Set end)

                //  *** End programmer edit section *** (Book.Topic Set end)
            }
        }
        
        /// <summary>
        /// Corrector.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Corrector CustomAttributes)

        //  *** End programmer edit section *** (Book.Corrector CustomAttributes)
        [StrLen(255)]
        public virtual string Corrector
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Corrector Get start)

                //  *** End programmer edit section *** (Book.Corrector Get start)
                string result = this.fCorrector;
                //  *** Start programmer edit section *** (Book.Corrector Get end)

                //  *** End programmer edit section *** (Book.Corrector Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Corrector Set start)

                //  *** End programmer edit section *** (Book.Corrector Set start)
                this.fCorrector = value;
                //  *** Start programmer edit section *** (Book.Corrector Set end)

                //  *** End programmer edit section *** (Book.Corrector Set end)
            }
        }
        
        /// <summary>
        /// Format.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Format CustomAttributes)

        //  *** End programmer edit section *** (Book.Format CustomAttributes)
        [StrLen(255)]
        public virtual string Format
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Format Get start)

                //  *** End programmer edit section *** (Book.Format Get start)
                string result = this.fFormat;
                //  *** Start programmer edit section *** (Book.Format Get end)

                //  *** End programmer edit section *** (Book.Format Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Format Set start)

                //  *** End programmer edit section *** (Book.Format Set start)
                this.fFormat = value;
                //  *** Start programmer edit section *** (Book.Format Set end)

                //  *** End programmer edit section *** (Book.Format Set end)
            }
        }
        
        /// <summary>
        /// Font.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Font CustomAttributes)

        //  *** End programmer edit section *** (Book.Font CustomAttributes)
        [StrLen(255)]
        public virtual string Font
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Font Get start)

                //  *** End programmer edit section *** (Book.Font Get start)
                string result = this.fFont;
                //  *** Start programmer edit section *** (Book.Font Get end)

                //  *** End programmer edit section *** (Book.Font Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Font Set start)

                //  *** End programmer edit section *** (Book.Font Set start)
                this.fFont = value;
                //  *** Start programmer edit section *** (Book.Font Set end)

                //  *** End programmer edit section *** (Book.Font Set end)
            }
        }
        
        /// <summary>
        /// PublishDate.
        /// </summary>
        //  *** Start programmer edit section *** (Book.PublishDate CustomAttributes)

        //  *** End programmer edit section *** (Book.PublishDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime PublishDate
        {
            get
            {
                //  *** Start programmer edit section *** (Book.PublishDate Get start)

                //  *** End programmer edit section *** (Book.PublishDate Get start)
                System.DateTime result = this.fPublishDate;
                //  *** Start programmer edit section *** (Book.PublishDate Get end)

                //  *** End programmer edit section *** (Book.PublishDate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.PublishDate Set start)

                //  *** End programmer edit section *** (Book.PublishDate Set start)
                this.fPublishDate = value;
                //  *** Start programmer edit section *** (Book.PublishDate Set end)

                //  *** End programmer edit section *** (Book.PublishDate Set end)
            }
        }
        
        /// <summary>
        /// Bestseller.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Bestseller CustomAttributes)

        //  *** End programmer edit section *** (Book.Bestseller CustomAttributes)
        [NotNull()]
        public virtual bool Bestseller
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Bestseller Get start)

                //  *** End programmer edit section *** (Book.Bestseller Get start)
                bool result = this.fBestseller;
                //  *** Start programmer edit section *** (Book.Bestseller Get end)

                //  *** End programmer edit section *** (Book.Bestseller Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Bestseller Set start)

                //  *** End programmer edit section *** (Book.Bestseller Set start)
                this.fBestseller = value;
                //  *** Start programmer edit section *** (Book.Bestseller Set end)

                //  *** End programmer edit section *** (Book.Bestseller Set end)
            }
        }
        
        /// <summary>
        /// Book.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Language CustomAttributes)

        //  *** End programmer edit section *** (Book.Language CustomAttributes)
        [PropertyStorage(new string[] {
                "Language"})]
        [NotNull()]
        public virtual NewPlatform.TestGenDefault.Language Language
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Language Get start)

                //  *** End programmer edit section *** (Book.Language Get start)
                NewPlatform.TestGenDefault.Language result = this.fLanguage;
                //  *** Start programmer edit section *** (Book.Language Get end)

                //  *** End programmer edit section *** (Book.Language Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Language Set start)

                //  *** End programmer edit section *** (Book.Language Set start)
                this.fLanguage = value;
                //  *** Start programmer edit section *** (Book.Language Set end)

                //  *** End programmer edit section *** (Book.Language Set end)
            }
        }
        
        /// <summary>
        /// Book.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Author CustomAttributes)

        //  *** End programmer edit section *** (Book.Author CustomAttributes)
        [PropertyStorage(new string[] {
                "Author"})]
        [NotNull()]
        public virtual NewPlatform.TestGenDefault.Author Author
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Author Get start)

                //  *** End programmer edit section *** (Book.Author Get start)
                NewPlatform.TestGenDefault.Author result = this.fAuthor;
                //  *** Start programmer edit section *** (Book.Author Get end)

                //  *** End programmer edit section *** (Book.Author Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Author Set start)

                //  *** End programmer edit section *** (Book.Author Set start)
                this.fAuthor = value;
                //  *** Start programmer edit section *** (Book.Author Set end)

                //  *** End programmer edit section *** (Book.Author Set end)
            }
        }
        
        /// <summary>
        /// Book.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Country CustomAttributes)

        //  *** End programmer edit section *** (Book.Country CustomAttributes)
        [PropertyStorage(new string[] {
                "Country"})]
        public virtual NewPlatform.TestGenDefault.Country Country
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Country Get start)

                //  *** End programmer edit section *** (Book.Country Get start)
                NewPlatform.TestGenDefault.Country result = this.fCountry;
                //  *** Start programmer edit section *** (Book.Country Get end)

                //  *** End programmer edit section *** (Book.Country Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Country Set start)

                //  *** End programmer edit section *** (Book.Country Set start)
                this.fCountry = value;
                //  *** Start programmer edit section *** (Book.Country Set end)

                //  *** End programmer edit section *** (Book.Country Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BookE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookE", typeof(NewPlatform.TestGenDefault.Book));
                }
            }
            
            /// <summary>
            /// "BookL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookL", typeof(NewPlatform.TestGenDefault.Book));
                }
            }
        }
    }
}
